<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-TLB4NBT" name="com.test.UIAutomation.HomePage.TC_002" tests="7" failures="0" timestamp="15 Jul 2017 22:50:36 GMT" time="36.162" errors="1">
  <testcase name="VerifyloginApplication" time="6.443" classname="com.test.UIAutomation.HomePage.TC_002"/>
  <testcase name="VerifyloginApplication" time="4.969" classname="com.test.UIAutomation.HomePage.TC_002"/>
  <testcase name="VerifyloginApplication" time="0.000" classname="com.test.UIAutomation.HomePage.TC_002">
    <error type="org.testng.SkipException" message="Not able to run">
      <![CDATA[org.testng.SkipException: Not able to run
	at com.test.UIAutomation.HomePage.TC_002.VerifyloginApplication(TC_002.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- VerifyloginApplication -->
  <testcase name="VerifyloginApplication" time="6.436" classname="com.test.UIAutomation.HomePage.TC_002"/>
  <testcase name="VerifyloginApplication" time="4.983" classname="com.test.UIAutomation.HomePage.TC_002"/>
  <testcase name="VerifyloginApplication" time="5.009" classname="com.test.UIAutomation.HomePage.TC_002"/>
  <testcase name="VerifyloginApplication" time="8.322" classname="com.test.UIAutomation.HomePage.TC_002"/>
</testsuite> <!-- com.test.UIAutomation.HomePage.TC_002 -->
